version: "3"

services:
  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: botCalDav
      POSTGRES_PASSWORD: admin
  nextcloud_caldav:
    image: nextcloud:latest
    ports:
      - "8080:80"